SDL = import("SDL");
GalRun = state extend SDL.Base {
    onLeftClick = func (x, y) {
        //TODO
    };
    onRightClick = func (x, y) {
        //TODO
    };
    onKeyDown = func (key) {
        //TODO
    };
    onKeyUp = func (key) {
        //TODO
    };
    onRedraw = func (drawer) {
        //TODO
    }
};

GalSetting = state extend SDL.Base {
    onLeftClick = func (x, y) {
        //TODO
    };
    onRightClick = func (x, y) {
        //TODO
    };
    onKeyDown = func (key) {
        //TODO
    };
    onKeyUp = func (key) {
        //TODO
    };
    onRedraw = func (drawer) {
        //TODO
    }
};

GalBegin = state extend SDL.Base {
    onLeftClick = func (x, y) {
        //TODO
    };
    onRightClick = func (x, y) {
        //TODO
    };
    onKeyDown = func (key) {
        //TODO
    };
    onKeyUp = func (key) {
        //TODO
    };
    onRedraw = func (drawer) {
        //TODO
    }
};

x = GalBegin();

SDL.run(x);
